-- Issue #40: let the lobby distinguish "server temporarily unresponsive" from
-- "server process restarted, session lost" without guessing from health checks alone.
--
-- A game server that crashes and comes back up passes the lobby's health check again
-- under the same domain/port, so a heartbeat alone cannot tell the lobby whether the
-- process that hosted a session is still the same process. Each game server generates
-- a fresh opaque instance id on every boot and reports it here; the lobby compares the
-- value stored on a match ticket against the current value on public.servers to decide
-- whether the hosting process has restarted (session lost).
--
-- Ownership of the new column:
--   instance_id  written by game,  read by lobby
--
-- Idempotent: re-running the migration on a database that already has the column
-- is a no-op.

ALTER TABLE public.servers
    ADD COLUMN IF NOT EXISTS instance_id VARCHAR(64);

-- Existing rows intentionally keep instance_id = NULL. NULL means "this server has not
-- reported an instance id yet" (old server build predating this column), not "no
-- restart happened". The lobby must not treat NULL as evidence of a restart; instead it
-- must fall back to querying session liveness directly. Do not backfill an arbitrary
-- value: a fabricated id would make the lobby either falsely detect a restart on next
-- comparison or falsely suppress one.
COMMENT ON COLUMN public.servers.instance_id IS
    'Opaque identifier regenerated by the game server on every process boot. Written by game; read by lobby, which compares it against the value stored on a match ticket to detect whether the hosting process restarted (session lost). NULL means the server has not reported an instance id yet (old server build); the lobby must then fall back to querying session liveness and must NOT treat NULL as a restart.';
