name: migrate

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Migrate with flyway
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/flyway/sql \
            redgate/flyway:latest \
            -url=$ {{ secrets.DB_URL }} \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASSWORD }} \
            -baselineOnMigrate=true \
            migrate
